//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Address
    {
        public int AddressId { get; set; }
        public Nullable<int> AddressTypeId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ContryId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string PostalCode { get; set; }
        public string Street { get; set; }
        public string House { get; set; }
        public string Housing { get; set; }
        public string ApartmentOffice { get; set; }
    
        public virtual dic_AddressType dic_AddressType { get; set; }
    }
}
