//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_model.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AvisWeb1Entities : DbContext
    {
        public AvisWeb1Entities()
            : base("name=AvisWeb1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<dic_AddressType> dic_AddressType { get; set; }
        public virtual DbSet<dic_Bank> dic_Bank { get; set; }
        public virtual DbSet<dic_City> dic_City { get; set; }
        public virtual DbSet<dic_Country> dic_Country { get; set; }
        public virtual DbSet<dic_Currency> dic_Currency { get; set; }
        public virtual DbSet<dic_PhoneType> dic_PhoneType { get; set; }
        public virtual DbSet<Phone> Phones { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
