//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_City
    {
        public int CityId { get; set; }
        public string GUID { get; set; }
        public string Name { get; set; }
        public string Name_En { get; set; }
        public string Name_Kk { get; set; }
        public string Name_Uz { get; set; }
        public string Name_Kg { get; set; }
        public string GUIDCountry { get; set; }
        public Nullable<bool> IsThereBranch { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string CityCode { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
