//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_City
    {
        public int CityId { get; set; }
        public string GUID { get; set; }
        public string Name { get; set; }
        public string Name_En { get; set; }
        public string Name_Kk { get; set; }
        public string Name_Uz { get; set; }
        public string Name_Kg { get; set; }
        public string GUIDCountry { get; set; }
        public Nullable<bool> IsThereBranch { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string CityCode { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
