//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class dic_Bank
    {
        public int BankId { get; set; }
        public string Name { get; set; }
        public string Bik { get; set; }
        public Nullable<System.DateTime> ChangeDate { get; set; }
        public string GuidBank { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
