//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PhoneId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PhoneTypeId { get; set; }
        public string СountryСode { get; set; }
        public string PhoneNumber { get; set; }
        public string AddNumber { get; set; }
        public string PhoneCode { get; set; }
    
        public virtual dic_PhoneType dic_PhoneType { get; set; }
        public virtual User User { get; set; }
    }
}
