//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBase_model.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phone
    {
        public int PhoneId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> PhoneTypeId { get; set; }
        public string СountryСode { get; set; }
        public string PhoneNumber { get; set; }
        public string AddNumber { get; set; }
        public string PhoneCode { get; set; }
    
        public virtual dic_PhoneType dic_PhoneType { get; set; }
    }
}
